## Лабораторная работа 2. Матрицы.


**Задание 1.**

Задайте матрицу
$$
A = \begin{bmatrix}
1 & 1 & 3\\
5 & 2 & 6\\
-2& -1& -3
\end{bmatrix}.
$$

(a) Найдите $A^3$.

(b) Замените третий столбец матрицы $A$ на сумму второго и третьего столбцов.

In [ ]:
A <- matrix(c(1, 1, 3, 5, 2, 6, -2, -1, -3), nrow = 3, byrow = T)
A
print("a)")
A %*% A %*% A
print("b)")
A[, 3] <- A[, 2] + A[, 3]
A

[,1] [,2] [,3]
[1,]  1    1    3  
[2,]  5    2    6  
[3,] -2   -1   -3

[1] "a)"


[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

[1] "b)"


[,1] [,2] [,3]
[1,]  1    1    4  
[2,]  5    2    8  
[3,] -2   -1   -4



---



**Задание 2.**

Создайте матрицу $B$ с 15 строками следующего вида:
$$
B = \begin{bmatrix}
10 & -10 & 10\\
10 & -10 & 10\\\
... & ... & ...\\
10 & -10 & 10
\end{bmatrix}.
$$

Вычислите матрицу $B^T B$ (размерности 3х3).

In [ ]:
B <- matrix(c(10, -10, 10), nrow = 15, ncol = 3, byrow = T)
t(B) %*% B

[,1]  [,2]  [,3] 
[1,]  1500 -1500  1500
[2,] -1500  1500 -1500
[3,]  1500 -1500  1500



---



** *Курсив*Задание 3.**
Создайте матрицу $E$ размерности 6х6, все элементы которой равны нулю. Изучите, что возвращают функции row() и col() применительно к матрице $E$. С помощью этих функций создайте следующие матрицы размерности 6х6:

(a)
$\begin{bmatrix}
0 & 1 & 0 & 0 & 0 & 0\\
1 & 0 & 1 & 0 & 0 & 0\\
0 & 1 & 0 & 1 & 0 & 0\\
0 & 0 & 1 & 0 & 1 & 0\\
0 & 0 & 0 & 1 & 0 & 1\\
0 & 0 & 0 & 0 & 1 & 0
\end{bmatrix}$,
(b)
$\begin{bmatrix}
1 & 0 & 1 & 0 & 0 & 0\\
0 & 1 & 0 & 1 & 0 & 0\\
1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1\\
0 & 0 & 1 & 0 & 1 & 0\\
0 & 0 & 0 & 1 & 0 & 1
\end{bmatrix}$,
(c)
$\begin{bmatrix}
0 & 0 & 0 & 1 & 0 & 1\\
0 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 0\\
1 & 0 & 1 & 0 & 0 & 0
\end{bmatrix}$.


In [ ]:
E <- matrix(0, nrow = 6, ncol = 6)
E
print("a)")
a <- (row(E) == col(E) - 1) | (row(E) == col(E) + 1)
res <- a
res[] <- as.integer(a)
res
print("b)")
b <- (row(E) == col(E)) | row(E) == col(E) - 2 | row(E) == col(E) + 2
res <- b
res[] <- as.integer(b)
res
print("c)")
E[row(E) + col(E) == 7] <- 1
E[row(E) + col(E) == 5] <- 1
E[row(E) + col(E) == 9] <- 1
E

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0    0    0    0    0    0   
[2,] 0    0    0    0    0    0   
[3,] 0    0    0    0    0    0   
[4,] 0    0    0    0    0    0   
[5,] 0    0    0    0    0    0   
[6,] 0    0    0    0    0    0

[1] "a)"


[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0    1    0    0    0    0   
[2,] 1    0    1    0    0    0   
[3,] 0    1    0    1    0    0   
[4,] 0    0    1    0    1    0   
[5,] 0    0    0    1    0    1   
[6,] 0    0    0    0    1    0

[1] "b)"


[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0    1    0    0    0   
[2,] 0    1    0    1    0    0   
[3,] 1    0    1    0    1    0   
[4,] 0    1    0    1    0    1   
[5,] 0    0    1    0    1    0   
[6,] 0    0    0    1    0    1

[1] "c)"


[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0    0    0    1    0    1   
[2,] 0    0    1    0    1    0   
[3,] 0    1    0    1    0    1   
[4,] 1    0    1    0    1    0   
[5,] 0    1    0    1    0    0   
[6,] 1    0    1    0    0    0



---



**Задание 4.**
Изучите справку по команде outer(). Создайте матрицы следующей структуры:

(a) $\begin{bmatrix}
0 & 1 & 2 & 3 & 4\\
1 & 2 & 3 & 4 & 5\\
2 & 3 & 4 & 5 & 6\\
3 & 4 & 5 & 6 & 7\\
4 & 5 & 6 & 7 & 8
\end{bmatrix}$,
(b) $\begin{bmatrix}
0 & 0 & 0 & 0 & 0\\
1 & 1 & 1 & 1 & 1\\
2 & 4 & 8 & 16 & 32\\
3 & 9 & 27 & 81 & 243\\
4 & 16 & 64 & 256 & 1024
\end{bmatrix}$.


In [ ]:
print("a)")
a <- outer(seq(0, 4), seq(0, 4), FUN = '+')
a
print("b)")
b <- outer(seq(0, 4), seq(0, 4) + 1, FUN = "^")
b

[1] "a)"


[,1] [,2] [,3] [,4] [,5]
[1,] 0    1    2    3    4   
[2,] 1    2    3    4    5   
[3,] 2    3    4    5    6   
[4,] 3    4    5    6    7   
[5,] 4    5    6    7    8

[1] "b)"


[,1] [,2] [,3] [,4] [,5]
[1,] 0     0    0     0     0
[2,] 1     1    1     1     1
[3,] 2     4    8    16    32
[4,] 3     9   27    81   243
[5,] 4    16   64   256  1024



---



**Задание 5.** Создайте матрицы следующих структур. В каждом случае ваше решение должно быть легко обобщаемым на случай создания матриц большей размерности, но той же структуры (т.е. матрицы должны создаваться не просто "впечатыванием" каждого элемента).

(a) $\begin{bmatrix}
0 & 1 & 2 & 3 & 4\\
1 & 2 & 3 & 4 & 0\\
2 & 3 & 4 & 0 & 1\\
3 & 4 & 0 & 1 & 2\\
4 & 0 & 1 & 2 & 3
\end{bmatrix}$,
(b) $\begin{bmatrix}
0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\\
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 0\\
... & ... & ... & ... & ... & ... & ... & ... & ... & ...\\
8 & 9 & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7\\
9 & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8
\end{bmatrix}$,

(c) $\begin{bmatrix}
0 & 8 & 7 & 6 & 5 & 4 & 3 & 2 & 1\\
1 & 0 & 8 & 7 & 6 & 5 & 4 & 3 & 2\\
2 & 1 & 0 & 8 & 7 & 6 & 5 & 4 & 3\\
3 & 2 & 1 & 0 & 8 & 7 & 6 & 5 & 4\\
4 & 3 & 2 & 1 & 0 & 8 & 7 & 6 & 5\\
5 & 4 & 3 & 2 & 1 & 0 & 8 & 7 & 6\\
6 & 5 & 4 & 3 & 2 & 1 & 0 & 8 & 7\\
7 & 6 & 5 & 4 & 3 & 2 & 1 & 0 & 8\\
8 & 7 & 6 & 5 & 4 & 3 & 2 & 1 & 0
\end{bmatrix}$.

In [ ]:
print("a)")
n <- 5
matrix(outer(0:(n-1), 0:(n-1), "+") %% n, nrow = n)
print("b)")
n <- 10
b <- matrix(0, n, n)
b <- outer(0:(n-1), 0:(n-1), function(x,y) (x + y) %% n)
b
print("c)")
n <- 9
c <- matrix(0, n, n)
c <- outer(0:(n-1), 0:(n-1), function(x,y) abs(x - y) %% n)
c

[1] "a)"


[,1] [,2] [,3] [,4] [,5]
[1,] 0    1    2    3    4   
[2,] 1    2    3    4    0   
[3,] 2    3    4    0    1   
[4,] 3    4    0    1    2   
[5,] 4    0    1    2    3

[1] "b)"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 0    1    2    3    4    5    6    7    8    9    
 [2,] 1    2    3    4    5    6    7    8    9    0    
 [3,] 2    3    4    5    6    7    8    9    0    1    
 [4,] 3    4    5    6    7    8    9    0    1    2    
 [5,] 4    5    6    7    8    9    0    1    2    3    
 [6,] 5    6    7    8    9    0    1    2    3    4    
 [7,] 6    7    8    9    0    1    2    3    4    5    
 [8,] 7    8    9    0    1    2    3    4    5    6    
 [9,] 8    9    0    1    2    3    4    5    6    7    
[10,] 9    0    1    2    3    4    5    6    7    8

[1] "c)"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,] 0    1    2    3    4    5    6    7    8   
 [2,] 1    0    1    2    3    4    5    6    7   
 [3,] 2    1    0    1    2    3    4    5    6   
 [4,] 3    2    1    0    1    2    3    4    5   
 [5,] 4    3    2    1    0    1    2    3    4   
 [6,] 5    4    3    2    1    0    1    2    3   
 [7,] 6    5    4    3    2    1    0    1    2   
 [8,] 7    6    5    4    3    2    1    0    1   
 [9,] 8    7    6    5    4    3    2    1    0



---



**Задание 6.** Решите следующую систему линейных уравнений с 5 неизвестными:

$$
\left\{
    \begin{array}{l}
        x_1 + 2x_2 + 3x_3 +4x_4 + 5x_5 = 7 &\\
        2x_1 + x_2 + 2x_3 + 3x_4 + 4x_5 = -1\\
        3x_1 + 2x_2 +x_3 + 2x_4 + 3x_5 = -3\\
        4x_1 + 3x_2 + 2x_3 + x_4 + 2x_5 = 5\\
        5x_1 + 4x_2 + 3x_3 + 2x_4 + x_5 = 17
    \end{array}
\right.,
$$
рассмотрев соответствующее матричное уравнение $Ax = y$ (см. функцию solve()). Обратите внимание на особый вид матрицы $A$. Метод, используемый для решения данной системы уравнений, должен быть легко обобщаем на случай большего числа уравнений, где матрица $A$ будет иметь такую же структуру.


In [ ]:
n <- 5
A <- matrix(0, ncol = 5, nrow = 5);
A <- matrix(abs(row(A) - col(A)) + 1, ncol = 5, nrow = 5)
A
y <- c(7, -1, -3, 5, 17)
solve(A, y)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 2    1    2    3    4   
[3,] 3    2    1    2    3   
[4,] 4    3    2    1    2   
[5,] 5    4    3    2    1

[1] -2  3  5  2 -4



---



**Задание 7.**
Создайте матрицу $M$ размерности 6х10, элементами которой являются целые числа, выбранные случайным образом с повторениями (см. функцию sample()) из совокупности $1,2,...,10$. Перед генерацией случайной выборки обеспечьте её воспроизводимость (с помощью команды set.seed(), которая фиксирует число, служащее начальной точкой для запуска алгоритма генерации (псевдо-)случайных чисел, для того, чтобы каждый раз при использовании генератора псевдо-случайных чисел получать идентичные последовательности чисел). Например, задайте set.seed(75).

(a) Найдите число элементов в каждой строке матрицы $M$, которые больше 4.

(b) В каких строках матрицы $M$ число 7 встречается ровно 2 раза?

(c) Найдите все пары столбцов матрицы $M$, сумма элементов которых больше 75. Ответом должна быть матрица с двумя столбцами, строки которой интерпретируются как пары номеров столбцов исходной матрицы $M$. Например, строка (1, 2) полученной матрицы означает, что сумма элементов по столбцам 1 и 2 матрицы $M$ больше 75. Полученная матрица вполне может содержать повторения пар (например, (1, 2) и (2, 1) и (2, 2).)  Исправьте решение, чтобы результат не содержал повторов.




---



**Задание 8.** Вычислите:

(a) $\sum\limits_{i=1}^{20}\sum\limits_{j=1}^5 \frac{i^4}{(3+j)}$,
(b) $\sum\limits_{i=1}^{20}\sum\limits_{j=1}^5 \frac{i^4}{(3+ij)}$.

In [ ]:
print("a)")
a <- sum(sapply(1:20, function(i) {
  sum(i^4 / (3 + 1:5))
}))
a
print("b)")
b <- sum(sapply(1:20, function(i) {
  sum(i^4 / (3 + i * 1:5))
}))
b

[1] "a)"


[1] 639215.3

[1] "b)"


[1] 89912.02